[package]
name = "yuzkkj/player-data-manager"
version = "0.2.9"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "ProfileStore and Replica wrapper for player data management"
homepage = "https://create.roblox.com/store/asset/123892997716567/PlayerDataManager"
repository = "https://github.com/Yuzkkj/player-data-manager"
license = "MIT"
authors = ["Yuz"]
exclude = ["**"]
include = [
    "default.project.json",
    "src",
    "src/**",
    "wally.toml",
]